# Generated by Django 2.0.2 on 2018-07-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KT1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attached', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('total_wins', models.DecimalField(decimal_places=1, max_digits=4)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Keibajou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='KeibaReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attached', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('Hitting', models.FloatField()),
            ],
        ),
    ]
