# Generated by Django 2.0.2 on 2018-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KT1', '0002_jockey_keibajou_keibareporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey',
            name='total_wins',
            field=models.IntegerField(),
        ),
    ]
