# Generated by Django 2.0.5 on 2018-08-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KT1', '0003_auto_20180729_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.FileField(upload_to='model_data')),
            ],
        ),
    ]
