# Generated by Django 2.0.5 on 2019-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KT1', '0004_jsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHoldingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=20)),
                ('race_name', models.CharField(max_length=30)),
            ],
        ),
    ]
